### ISSUE TITLE
webpackJsonp

### ISSUE THREAD

**Issue by FireMonkey** [boehlergerman/WappBot#7]
Hello there ,

I get an error after installing the wappbot.js file.

Uncaught TypeError: webpackJsonp is not a function.

What can i do ?

Thank you

**Comment by boehlergerman** [comment]
Hello.

Thanks for telling me, apparently Whatsapp Web changed the structure that I used in the function "webpackJsonp" which is where all the modules needed to perform the different actions.

I uploaded a new version that includes these changes, so that it continues to work as before.
#8 

Please, try it and if it doesn't work I will investigate another solution.

Thank you.

**Comment by FireMonkey** [comment]
It's work ! Thank you for your efforts :)
